-- =====================================================
-- DEPLOYMENT PORTAL DATABASE SCHEMA
-- Enterprise DDL Script for PostgreSQL/Oracle
-- Schema Owner: DPOWNER
-- =====================================================

-- =====================================================
-- TABLE: DP_USERS
-- Description: User authentication and role management
-- =====================================================
CREATE TABLE DPOWNER.DP_USERS (
    USERNAME NVARCHAR2(50) NOT NULL,
    PASSWORD NVARCHAR2(255) NOT NULL,
    USER_ROLE NVARCHAR2(20) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN TIMESTAMP,
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    PRIMARY KEY (USERNAME)
) TABLESPACE DP01_T;

-- Create public synonym
CREATE PUBLIC SYNONYM DP_USERS FOR DPOWNER.DP_USERS;

-- Create indexes
CREATE INDEX DPOWNER.IDX_DP_USERS_ROLE ON DPOWNER.DP_USERS (USER_ROLE) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_USERS_ACTIVE ON DPOWNER.DP_USERS (IS_ACTIVE) TABLESPACE DP01_I;

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON DPOWNER.DP_USERS TO DPSECID;
GRANT SELECT ON DPOWNER.DP_USERS TO DPREADID;

-- =====================================================
-- TABLE: DP_SERVICES
-- Description: Catalog of deployable services
-- =====================================================
CREATE TABLE DPOWNER.DP_SERVICES (
    SERVICE_ID NUMBER(19) NOT NULL,
    SERVICE_NAME NVARCHAR2(100) NOT NULL,
    SERVICE_CATEGORY NVARCHAR2(50),
    SERVICE_DESCRIPTION NVARCHAR2(500),
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (SERVICE_ID)
) TABLESPACE DP01_T;

-- Create sequence for auto-increment
CREATE SEQUENCE DPOWNER.SEQ_DP_SERVICES_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create public synonym
CREATE PUBLIC SYNONYM DP_SERVICES FOR DPOWNER.DP_SERVICES;

-- Create indexes
CREATE UNIQUE INDEX DPOWNER.UNQ_DP_SERVICES_NAME ON DPOWNER.DP_SERVICES (SERVICE_NAME) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_SERVICES_CATEGORY ON DPOWNER.DP_SERVICES (SERVICE_CATEGORY) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_SERVICES_ACTIVE ON DPOWNER.DP_SERVICES (IS_ACTIVE) TABLESPACE DP01_I;

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON DPOWNER.DP_SERVICES TO DPSECID;
GRANT SELECT ON DPOWNER.DP_SERVICES TO DPREADID;
GRANT SELECT ON DPOWNER.SEQ_DP_SERVICES_ID TO DPSECID;

-- =====================================================
-- TABLE: DP_RELEASES
-- Description: Release management with YYYY-MM format
-- =====================================================
CREATE TABLE DPOWNER.DP_RELEASES (
    RELEASE_ID NUMBER(19) NOT NULL,
    RELEASE_NAME NVARCHAR2(7) NOT NULL,
    RELEASE_DESCRIPTION NVARCHAR2(1000) NOT NULL,
    RELEASE_STATUS NVARCHAR2(20) DEFAULT 'PLANNED',
    START_DATE DATE,
    END_DATE DATE,
    CREATED_BY NVARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (RELEASE_ID)
) TABLESPACE DP01_T;

-- Create sequence for auto-increment
CREATE SEQUENCE DPOWNER.SEQ_DP_RELEASES_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create public synonym
CREATE PUBLIC SYNONYM DP_RELEASES FOR DPOWNER.DP_RELEASES;

-- Create indexes
CREATE UNIQUE INDEX DPOWNER.UNQ_DP_RELEASES_NAME ON DPOWNER.DP_RELEASES (RELEASE_NAME) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_RELEASES_STATUS ON DPOWNER.DP_RELEASES (RELEASE_STATUS) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_RELEASES_CREATED_BY ON DPOWNER.DP_RELEASES (CREATED_BY) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_RELEASES_DATES ON DPOWNER.DP_RELEASES (START_DATE, END_DATE) TABLESPACE DP01_I;

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON DPOWNER.DP_RELEASES TO DPSECID;
GRANT SELECT ON DPOWNER.DP_RELEASES TO DPREADID;
GRANT SELECT ON DPOWNER.SEQ_DP_RELEASES_ID TO DPSECID;

-- =====================================================
-- TABLE: DP_DEPLOYMENT_REQUESTS
-- Description: Core deployment request tracking
-- =====================================================
CREATE TABLE DPOWNER.DP_DEPLOYMENT_REQUESTS (
    REQUEST_ID NUMBER(19) NOT NULL,
    SERIAL_NUMBER NVARCHAR2(20),
    CSI_ID NVARCHAR2(50),
    SERVICE_NAME NVARCHAR2(100) NOT NULL,
    BUSINESS_REQUEST_ID NVARCHAR2(100),
    UPCOMING_BRANCH NVARCHAR2(200),
    IS_CONFIG_REQUEST CHAR(1) DEFAULT 'N',
    CONFIG_REQUEST_ID NVARCHAR2(100),
    CONFIG_UPCOMING_BRANCH NVARCHAR2(200),
    RELEASE_BRANCH NVARCHAR2(200),
    DEVELOPMENT_TEAM NVARCHAR2(100),
    REQUEST_STATUS NVARCHAR2(20) DEFAULT 'OPEN',
    RELEASE_NAME NVARCHAR2(7),
    PRODUCTION_READY_FLAG CHAR(1) DEFAULT 'N',
    CREATED_BY NVARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    APPROVED_BY NVARCHAR2(50),
    APPROVED_DATE TIMESTAMP,
    PRIMARY KEY (REQUEST_ID)
) TABLESPACE DP01_T;

-- Create sequence for auto-increment
CREATE SEQUENCE DPOWNER.SEQ_DP_DEPLOYMENT_REQ_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create public synonym
CREATE PUBLIC SYNONYM DP_DEPLOYMENT_REQUESTS FOR DPOWNER.DP_DEPLOYMENT_REQUESTS;

-- Create indexes
CREATE UNIQUE INDEX DPOWNER.UNQ_DP_DEPLOY_SERIAL ON DPOWNER.DP_DEPLOYMENT_REQUESTS (SERIAL_NUMBER) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_DEPLOY_SERVICE ON DPOWNER.DP_DEPLOYMENT_REQUESTS (SERVICE_NAME) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_DEPLOY_STATUS ON DPOWNER.DP_DEPLOYMENT_REQUESTS (REQUEST_STATUS) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_DEPLOY_RELEASE ON DPOWNER.DP_DEPLOYMENT_REQUESTS (RELEASE_NAME) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_DEPLOY_TEAM ON DPOWNER.DP_DEPLOYMENT_REQUESTS (DEVELOPMENT_TEAM) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_DEPLOY_CREATED_BY ON DPOWNER.DP_DEPLOYMENT_REQUESTS (CREATED_BY) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_DEPLOY_CREATED_DATE ON DPOWNER.DP_DEPLOYMENT_REQUESTS (CREATED_DATE) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_DEPLOY_PROD_READY ON DPOWNER.DP_DEPLOYMENT_REQUESTS (PRODUCTION_READY_FLAG) TABLESPACE DP01_I;

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON DPOWNER.DP_DEPLOYMENT_REQUESTS TO DPSECID;
GRANT SELECT ON DPOWNER.DP_DEPLOYMENT_REQUESTS TO DPREADID;
GRANT SELECT ON DPOWNER.SEQ_DP_DEPLOYMENT_REQ_ID TO DPSECID;

-- =====================================================
-- TABLE: DP_DEPLOYMENT_ENVIRONMENTS
-- Description: Environment assignments for deployment requests
-- =====================================================
CREATE TABLE DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS (
    ENVIRONMENT_ID NUMBER(19) NOT NULL,
    REQUEST_ID NUMBER(19) NOT NULL,
    ENVIRONMENT_NAME NVARCHAR2(10) NOT NULL,
    ENVIRONMENT_STATUS NVARCHAR2(20) DEFAULT 'PENDING',
    RLM_ID NVARCHAR2(50),
    DEPLOYED_DATE TIMESTAMP,
    DEPLOYED_BY NVARCHAR2(50),
    ROLLBACK_FLAG CHAR(1) DEFAULT 'N',
    ROLLBACK_DATE TIMESTAMP,
    ROLLBACK_BY NVARCHAR2(50),
    PRIMARY KEY (ENVIRONMENT_ID)
) TABLESPACE DP01_T;

-- Create sequence for auto-increment
CREATE SEQUENCE DPOWNER.SEQ_DP_DEPLOY_ENV_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create public synonym
CREATE PUBLIC SYNONYM DP_DEPLOYMENT_ENVIRONMENTS FOR DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS;

-- Create indexes
CREATE INDEX DPOWNER.IDX_DP_DEPLOY_ENV_REQ_ID ON DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS (REQUEST_ID) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_DEPLOY_ENV_NAME ON DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS (ENVIRONMENT_NAME) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_DEPLOY_ENV_STATUS ON DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS (ENVIRONMENT_STATUS) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_DEPLOY_ENV_RLM ON DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS (RLM_ID) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_DEPLOY_ENV_DATE ON DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS (DEPLOYED_DATE) TABLESPACE DP01_I;

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS TO DPSECID;
GRANT SELECT ON DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS TO DPREADID;
GRANT SELECT ON DPOWNER.SEQ_DP_DEPLOY_ENV_ID TO DPSECID;

-- =====================================================
-- TABLE: DP_RLM_TRACKING
-- Description: RLM ID tracking for different environments
-- =====================================================
CREATE TABLE DPOWNER.DP_RLM_TRACKING (
    RLM_TRACKING_ID NUMBER(19) NOT NULL,
    REQUEST_ID NUMBER(19) NOT NULL,
    ENVIRONMENT_TYPE NVARCHAR2(10) NOT NULL,
    RLM_ID_UAT1 NVARCHAR2(50),
    RLM_ID_UAT2 NVARCHAR2(50),
    RLM_ID_UAT3 NVARCHAR2(50),
    RLM_ID_PERF1 NVARCHAR2(50),
    RLM_ID_PERF2 NVARCHAR2(50),
    RLM_ID_PROD1 NVARCHAR2(50),
    RLM_ID_PROD2 NVARCHAR2(50),
    UPDATED_BY NVARCHAR2(50),
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (RLM_TRACKING_ID)
) TABLESPACE DP01_T;

-- Create sequence for auto-increment
CREATE SEQUENCE DPOWNER.SEQ_DP_RLM_TRACKING_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create public synonym
CREATE PUBLIC SYNONYM DP_RLM_TRACKING FOR DPOWNER.DP_RLM_TRACKING;

-- Create indexes
CREATE INDEX DPOWNER.IDX_DP_RLM_REQUEST_ID ON DPOWNER.DP_RLM_TRACKING (REQUEST_ID) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_RLM_ENV_TYPE ON DPOWNER.DP_RLM_TRACKING (ENVIRONMENT_TYPE) TABLESPACE DP01_I;
CREATE INDEX DPOWNER.IDX_DP_RLM_UPDATED_DATE ON DPOWNER.DP_RLM_TRACKING (UPDATED_DATE) TABLESPACE DP01_I;

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON DPOWNER.DP_RLM_TRACKING TO DPSECID;
GRANT SELECT ON DPOWNER.DP_RLM_TRACKING TO DPREADID;
GRANT SELECT ON DPOWNER.SEQ_DP_RLM_TRACKING_ID TO DPSECID;

-- =====================================================
-- FOREIGN KEY CONSTRAINTS
-- =====================================================

-- DP_RELEASES foreign key to DP_USERS
ALTER TABLE DPOWNER.DP_RELEASES 
ADD CONSTRAINT FK_DP_RELEASES_CREATED_BY 
FOREIGN KEY (CREATED_BY) REFERENCES DPOWNER.DP_USERS(USERNAME);

-- DP_DEPLOYMENT_REQUESTS foreign key to DP_USERS
ALTER TABLE DPOWNER.DP_DEPLOYMENT_REQUESTS 
ADD CONSTRAINT FK_DP_DEPLOY_REQ_CREATED_BY 
FOREIGN KEY (CREATED_BY) REFERENCES DPOWNER.DP_USERS(USERNAME);

ALTER TABLE DPOWNER.DP_DEPLOYMENT_REQUESTS 
ADD CONSTRAINT FK_DP_DEPLOY_REQ_APPROVED_BY 
FOREIGN KEY (APPROVED_BY) REFERENCES DPOWNER.DP_USERS(USERNAME);

-- DP_DEPLOYMENT_ENVIRONMENTS foreign key to DP_DEPLOYMENT_REQUESTS
ALTER TABLE DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS 
ADD CONSTRAINT FK_DP_DEPLOY_ENV_REQUEST_ID 
FOREIGN KEY (REQUEST_ID) REFERENCES DPOWNER.DP_DEPLOYMENT_REQUESTS(REQUEST_ID) ON DELETE CASCADE;

-- DP_RLM_TRACKING foreign key to DP_DEPLOYMENT_REQUESTS
ALTER TABLE DPOWNER.DP_RLM_TRACKING 
ADD CONSTRAINT FK_DP_RLM_REQUEST_ID 
FOREIGN KEY (REQUEST_ID) REFERENCES DPOWNER.DP_DEPLOYMENT_REQUESTS(REQUEST_ID) ON DELETE CASCADE;

-- =====================================================
-- CHECK CONSTRAINTS
-- =====================================================

-- User role constraints
ALTER TABLE DPOWNER.DP_USERS 
ADD CONSTRAINT CHK_DP_USERS_ROLE 
CHECK (USER_ROLE IN ('DEVELOPER', 'ADMIN', 'SUPERADMIN'));

ALTER TABLE DPOWNER.DP_USERS 
ADD CONSTRAINT CHK_DP_USERS_ACTIVE 
CHECK (IS_ACTIVE IN ('Y', 'N'));

-- Service active constraint
ALTER TABLE DPOWNER.DP_SERVICES 
ADD CONSTRAINT CHK_DP_SERVICES_ACTIVE 
CHECK (IS_ACTIVE IN ('Y', 'N'));

-- Release status constraints
ALTER TABLE DPOWNER.DP_RELEASES 
ADD CONSTRAINT CHK_DP_RELEASES_STATUS 
CHECK (RELEASE_STATUS IN ('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED'));

-- Release name format constraint (YYYY-MM)
ALTER TABLE DPOWNER.DP_RELEASES 
ADD CONSTRAINT CHK_DP_RELEASES_NAME_FORMAT 
CHECK (REGEXP_LIKE(RELEASE_NAME, '^[0-9]{4}-[0-9]{2}$'));

-- Deployment request status constraints
ALTER TABLE DPOWNER.DP_DEPLOYMENT_REQUESTS 
ADD CONSTRAINT CHK_DP_DEPLOY_REQ_STATUS 
CHECK (REQUEST_STATUS IN ('OPEN', 'IN_PROGRESS', 'PENDING', 'COMPLETED', 'CANCELLED'));

ALTER TABLE DPOWNER.DP_DEPLOYMENT_REQUESTS 
ADD CONSTRAINT CHK_DP_DEPLOY_REQ_CONFIG 
CHECK (IS_CONFIG_REQUEST IN ('Y', 'N'));

ALTER TABLE DPOWNER.DP_DEPLOYMENT_REQUESTS 
ADD CONSTRAINT CHK_DP_DEPLOY_REQ_PROD_READY 
CHECK (PRODUCTION_READY_FLAG IN ('Y', 'N'));

-- Environment constraints
ALTER TABLE DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS 
ADD CONSTRAINT CHK_DP_DEPLOY_ENV_NAME 
CHECK (ENVIRONMENT_NAME IN ('UAT1', 'UAT2', 'UAT3', 'PERF1', 'PERF2', 'PROD1', 'PROD2'));

ALTER TABLE DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS 
ADD CONSTRAINT CHK_DP_DEPLOY_ENV_STATUS 
CHECK (ENVIRONMENT_STATUS IN ('PENDING', 'DEPLOYED', 'FAILED', 'ROLLED_BACK'));

ALTER TABLE DPOWNER.DP_DEPLOYMENT_ENVIRONMENTS 
ADD CONSTRAINT CHK_DP_DEPLOY_ENV_ROLLBACK 
CHECK (ROLLBACK_FLAG IN ('Y', 'N'));

-- =====================================================
-- INITIAL DATA INSERTION
-- =====================================================

-- Insert initial users
INSERT INTO DPOWNER.DP_USERS (USERNAME, PASSWORD, USER_ROLE, IS_ACTIVE) VALUES 
('ADMIN', 'admin123', 'ADMIN', 'Y');
INSERT INTO DPOWNER.DP_USERS (USERNAME, PASSWORD, USER_ROLE, IS_ACTIVE) VALUES 
('DEVELOPER1', 'dev123', 'DEVELOPER', 'Y');
INSERT INTO DPOWNER.DP_USERS (USERNAME, PASSWORD, USER_ROLE, IS_ACTIVE) VALUES 
('SUPERADMIN', 'super123', 'SUPERADMIN', 'Y');

-- Insert initial releases
INSERT INTO DPOWNER.DP_RELEASES (RELEASE_ID, RELEASE_NAME, RELEASE_DESCRIPTION, RELEASE_STATUS, CREATED_BY) VALUES 
(DPOWNER.SEQ_DP_RELEASES_ID.NEXTVAL, '2025-01', 'January 2025 Release - New authentication features', 'ACTIVE', 'ADMIN');
INSERT INTO DPOWNER.DP_RELEASES (RELEASE_ID, RELEASE_NAME, RELEASE_DESCRIPTION, RELEASE_STATUS, CREATED_BY) VALUES 
(DPOWNER.SEQ_DP_RELEASES_ID.NEXTVAL, '2025-02', 'February 2025 Release - Payment system enhancements', 'PLANNED', 'ADMIN');
INSERT INTO DPOWNER.DP_RELEASES (RELEASE_ID, RELEASE_NAME, RELEASE_DESCRIPTION, RELEASE_STATUS, CREATED_BY) VALUES 
(DPOWNER.SEQ_DP_RELEASES_ID.NEXTVAL, '2025-03', 'March 2025 Release - User experience improvements', 'PLANNED', 'ADMIN');

-- Sample services (first 20 of 180)
INSERT INTO DPOWNER.DP_SERVICES (SERVICE_ID, SERVICE_NAME, SERVICE_CATEGORY, IS_ACTIVE) VALUES 
(DPOWNER.SEQ_DP_SERVICES_ID.NEXTVAL, 'auth-login-service', 'AUTHENTICATION', 'Y');
INSERT INTO DPOWNER.DP_SERVICES (SERVICE_ID, SERVICE_NAME, SERVICE_CATEGORY, IS_ACTIVE) VALUES 
(DPOWNER.SEQ_DP_SERVICES_ID.NEXTVAL, 'auth-logout-service', 'AUTHENTICATION', 'Y');
INSERT INTO DPOWNER.DP_SERVICES (SERVICE_ID, SERVICE_NAME, SERVICE_CATEGORY, IS_ACTIVE) VALUES 
(DPOWNER.SEQ_DP_SERVICES_ID.NEXTVAL, 'pay-gateway-service', 'PAYMENT', 'Y');
INSERT INTO DPOWNER.DP_SERVICES (SERVICE_ID, SERVICE_NAME, SERVICE_CATEGORY, IS_ACTIVE) VALUES 
(DPOWNER.SEQ_DP_SERVICES_ID.NEXTVAL, 'user-profile-service', 'USER_MANAGEMENT', 'Y');
INSERT INTO DPOWNER.DP_SERVICES (SERVICE_ID, SERVICE_NAME, SERVICE_CATEGORY, IS_ACTIVE) VALUES 
(DPOWNER.SEQ_DP_SERVICES_ID.NEXTVAL, 'notif-email-service', 'NOTIFICATION', 'Y');

-- Commit all changes
COMMIT;

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================
SELECT 'DP_USERS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM DPOWNER.DP_USERS;
SELECT 'DP_SERVICES' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM DPOWNER.DP_SERVICES;
SELECT 'DP_RELEASES' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM DPOWNER.DP_RELEASES;

-- =====================================================
-- END OF SCRIPT
-- =====================================================
